### ISSUE TITLE
How do I connect number or logic values to the item transfers?

### ISSUE THREAD

**Issue by puggan** [MattiDragon/AdvancedNetworking#14]
### Description of the issue

I tried to limit the number of items transfered by taking the wanted amount minus the current amount, but don't seamto be able to connect an numeric value link to the limiter (or other item flow nodes)

![2024-01-01_13 23 52](https://github.com/MattiDragon/AdvancedNetworking/assets/866668/40d822bf-21b3-4b8b-9a10-9a1cf119fe83)

I also tried to use a less-then node, but the boolean value link can't be connected either. Tried to connect it to a switch-node but that node only takes numeric links.

![2024-01-01_13 22 42](https://github.com/MattiDragon/AdvancedNetworking/assets/866668/e1efb7ac-c31d-43f5-a2cc-237837de9af3)

### Reproduction steps

1. chest of fuel
2. furnace
3. network controller
4. connect all 3
5. configure the network controller

### Mod version

v3.0.1+mc1.20.4

### Operating System

Windows 10 home 22H2

### Minecraft version

1.20.4 fabric 0.15.3

### Other mods

![image](https://github.com/MattiDragon/AdvancedNetworking/assets/866668/07e6f941-7b8c-4c9c-b7a8-1dde57423ae5)

### Server

Not tested

### Client

Happens

### Logs

no entries logged during problem

**Comment by MattiDragon** [comment]
For the switch node you need to open the config and select the correct type. I might add an option for a value input to the limit nodes at some point

**Comment by puggan** [comment]
> a value input to the limit nodes

sounds great.

And got the switch working:

![image](https://github.com/MattiDragon/AdvancedNetworking/assets/866668/c9e28aed-74aa-4ee7-8f85-5bcd7cedb312)

You may want to add a list of exemple system, like the screenshoot above, to give an exemple on what the mod can do.

**Comment by TommyC81** [comment]
Thanks for this issue being available as a reference. I was pulling my hair trying to transfer items to meet a certain level in a chest. This works, but is somewhat convoluted for a relatively common use case. An (optional) value input into the limit node would make sense. Thank you!
