### ISSUE TITLE
More info on first glance

### ISSUE THREAD

**Issue by Knito58** [MattiDragon/AdvancedNetworking#15]
### Description of the feature

The nodes view is blank. To actually see what it does I have to click the button. It would be fine if "Cobble Chest" was written on the node for item source. And if "Furnace Input" was already visible on item target. Maybe the filter node could show some infos, too. Perhaps when hovering the mouse over it.

In my humble opinion all nodes would profit from being more informative.

### How does it make the mod better?

It would help me see my errors on first glance.

This mod already is one of the best. For functionality this features are not needed. Only for overall information.

**Comment by MattiDragon** [comment]
Could you explain more where and what kind of information you want? I could probably read the block name as a default for interfaces, but I'm unsure of what you mean by the rest

**Comment by Knito58** [comment]
![controller](https://github.com/MattiDragon/AdvancedNetworking/assets/2604989/c8ac4b21-d883-4b20-bbe3-11fd59f506c7)
This is how most of my controller views look like.

**Comment by Knito58** [comment]
Below "Item Source" it would be nice to see which interface name I hooked to the node. Same for Item Target.
"Filter Items" are probably more tricky. Maybe hovering over it would display the set filter.

**Comment by Knito58** [comment]
![controller1](https://github.com/MattiDragon/AdvancedNetworking/assets/2604989/a661e5fd-826d-4ce2-a1b3-7c2d84c7768e)
Maybe st like that.

**Comment by Knito58** [comment]
.... And if I deleted an interface or forgot to configure it: A "XXX no interface XXX" string in red would be nice.

**Comment by MattiDragon** [comment]
For the missing interface you should get a orange error config button which shows the error on hover

**Comment by Knito58** [comment]
I like your minimalistic approach: No fuzz, no problems!
I would have made the default string being the error message and only replace it when a valid interface is hooked to it.
I am very happy that you seem to consider this submission being worthy of thinking about it.

**Comment by MattiDragon** [comment]
I've added the option to rename nodes for the next update. You can see how it looks in my [latest discord showcase](https://discord.com/channels/760524772189798431/1035612386637385779/1197970728591568906)

**Comment by Knito58** [comment]
Oh - I didn't realize the thing with the nickname and was already pleased from using the groups feature. But now everything is wrapped up.
One little thing, yet: Please let all "done" buttons be executed on hitting "enter" or "return".
You may close my feature requests as being fulfilled.
Thank you very much.

**Comment by Knito58** [comment]
![image](https://github.com/MattiDragon/AdvancedNetworking/assets/2604989/b6a755b5-faa3-4e71-9f4a-67f301d64087)

**Comment by Knito58** [comment]
40 iron furnaces from tech reborn and 8 pulverizers are targeted in the above screen and everything runs just fine.
