### ISSUE TITLE
Group nodes into groups for simpler config

### ISSUE THREAD

**Issue by Knito58** [MattiDragon/AdvancedNetworking#16]
### Description of the feature

Any furnace or chest (item target or item source) should be able to belong to a group. Groups would be defined in the new "Groups" - tab on top of the controllers view.

Instead of nodes you could also add groups. And instead of configuring every possible way from this and that chest to those four furnaces you would say: From group "dust chests" to group "smelting furnaces" with filter "regex: ^energ.*dust$".
This would save a lot of entries and keep things clean in the controller view.

### How does it make the mod better?

Atm I'm struggling with the  "yet another cobble generator" mod and its ore generator. It creates ores so quickly that I am constantly adding more furnaces and more chests and more energized power "pulverizers" to keep up converting the items and ultimately storing them into the "extended drawers". It would be much easier if I only had to add new furnaces to the "smelters" group and another output chest for even more pulverizers to the "pulver chests" group. And the pulverizers as well in their own group. 
With singleton nodes I constantly am adding all the possible ways from new sources to old destinations. The duplicate feature of the nodes really helps with that but with groups the controller config would be much easier to config and to overview.

**Comment by MattiDragon** [comment]
If I would implement groups then it would probably be another field in the cable config where you can set a group (or merge with cables with the same name). Then you could in the node select a group instead of a single interface.

**Comment by Knito58** [comment]
Yep that sounds less complicated than my suggestion was. But it would work and there would be less clutter in the controller view. Great!

**Comment by MattiDragon** [comment]
I've added groups to the next update. You can see how it looks in my [latest discord showcase](https://discord.com/channels/760524772189798431/1035612386637385779/1197970728591568906)

**Comment by Knito58** [comment]
Wow! I just hang 8 Pulverizers in one Go!
Amazing! So good!
