### ISSUE TITLE
[Bug]: Configuring interface causes Network Cable to disappear/reapper and no changes saved.

### ISSUE THREAD

**Issue by TommyC81** [MattiDragon/AdvancedNetworking#18]
### Description of the issue

Minecraft 1.20.4 using Advanced Networking v3.1.0 [1.20.4] from 28 Jan 2024 (with many mods). Dedicated LAN server with LAN client (issue experienced on client, no error log on server).

Some issues:
1. Configuring a network can only be done with an empty hand. If you have a shield in the off-hand it doesn't work - you first have to remove the shield from the off hand and then sneak/right-click with nothing in any hands. Suggest to simply make it so that sneaking and right-clicking with a stick (or wrench) then you configure, makes it much more streamlined.
2. When configuring the interface, the Network Cable disappears. In the Cable configuration interface itself, no settings are saved (this can be noted by simply switching between the different directions i.e., NORTH/SOUTH/WEST etc.). When pressing escape to exit the Cable configurator, it appears that you're placing a interface and a left-click restores the Network Cable (but without any configuration applied).

Before opening Cable configurator:
![image](https://github.com/MattiDragon/AdvancedNetworking/assets/1904092/b551c0fc-36a6-4aa6-8bbd-8aa17a7b799f)

When opening the Cable configurator (note that the Network Cable is gone in the background):
![image](https://github.com/MattiDragon/AdvancedNetworking/assets/1904092/4296f83d-394d-432a-8761-fe2c72e43633)

Changing Cable configuration:
![image](https://github.com/MattiDragon/AdvancedNetworking/assets/1904092/83120d54-b872-443d-93ae-a96f182de260)

After click on 'South' and back to 'North' again, no settings remain (the final outcome of no settings saved is the same regardless if clicking another interface or not):
![image](https://github.com/MattiDragon/AdvancedNetworking/assets/1904092/3c022bd4-9f30-4b14-95ce-ce6e4182a233)

After pressing escape to close the Cable configurator, no interaction with anything else is possible including changing tool etc.:
![image](https://github.com/MattiDragon/AdvancedNetworking/assets/1904092/6b064ab7-ae8d-4a4c-9f12-104a969f563e)

A right-click restores the Network Cable without any settings saved:
![image](https://github.com/MattiDragon/AdvancedNetworking/assets/1904092/28909b4d-335b-441a-ab1d-6628ee44d882)

### Reproduction steps

See description.

### Mod version

v3.1.0 [1.20.4] from 28 Jan 2024

### Operating System

Windows 10

### Minecraft version

1.20.4

### Other mods

fabric-api-0.97.1+1.20.4

Many mods...
advanced-networking-3.1.0+mc.1.20.4.jar
AdvancementPlaques-1.20.4-fabric-1.6.1.jar
alternate-current-mc1.20-1.8.0-beta.4.jar
AmbientEnvironment-fabric-1.20.4-14.0.0.4.jar
animal_feeding_trough-1.0.3+1.20.4.jar
animatica-0.6.1+1.20.4.jar
appleskin-fabric-mc1.20.3-2.5.1.jar
ArcaneLanterns-v20.4.1-1.20.4-Fabric.jar
architectury-11.1.17-fabric.jar
areas-1.20.4-5.9.jar
ArmorStatues-v20.4.2-1.20.4-Fabric.jar
AttributeFix-Fabric-1.20.4-24.0.2.jar
auto-workstations-[MC1.20.4]-1.0-rc.22.jar
BadOptimizations-2.1.4-1.20.2-20.4.jar
badpackets-fabric-0.6.1.jar
balm-fabric-1.20.4-9.0.9.jar
BarteringStation-v20.4.1-1.20.4-Fabric.jar
beautify-1.2.1+1.20.4.jar
betterbeaconplacement-1.20.4-3.3.jar
bettercombat-fabric-1.8.6+1.20.4.jar
betterconduitplacement-1.20.4-3.2.jar
bettercrafting-1.20.4-16-fabric.jar
BetterF3-9.0.2-Fabric-1.20.4.jar
bettermounthud-1.2.2.jar
BetterPingDisplay-Fabric-1.20.4-1.1.1.jar
betterspawnercontrol-1.20.4-4.4.jar
betterstats-3.9.7+fabric-1.20.4.jar
bettertaskbar-fabric-mc1.20.2-1.8.0.jar
BetterThirdPerson-Fabric-1.20-1.9.0.jar
BetterTridents-v20.4.0-1.20.4-Fabric.jar
biggerspongeabsorptionradius-1.20.4-3.5.jar
blastingraw-1.20.4-2-fabric.jar
blastingsand-1.20.4-11-fabric.jar
BlockRunner-v20.4.1-1.20.4-Fabric.jar
bobby-5.1.0+mc1.20.4.jar
Bookshelf-Fabric-1.20.4-23.0.8.jar
bottledair-1.20.4-2.3.jar
bouncyblocks-0.2-1.20.4.jar
BowInfinityFix-1.20.x-fabric-2.6.0.jar
brandedlogs-2.0.1.jar
brb-1.10.0-rc5+1.20.4.jar
BridgingMod-2.3.0+1.20.4.fabric-release.jar
campfirespawnandtweaks-1.20.4-3.7.jar
capes-1.5.3+1.20.2-fabric.jar
carryon-fabric-1.20.4-2.1.3.13.jar
chat_heads-0.12.3-fabric-1.20.3.jar
cherishedworlds-fabric-8.0.1+1.20.4.jar
citresewn-1.1.5+1.20.4.jar
clayblasting-1.20.4-0-fabric.jar
cleanview-1.20.4-v1-fabric.jar
clickthrough-1.20.4-fabric0.91.2-0.4.1.jar
clienttweaks-fabric-1.20.4-13.0.2.jar
cloth-config-13.0.121-fabric.jar
Clumps-fabric-1.20.4-15.0.0.2.jar
collective-1.20.4-7.64.jar
combat-enchantments-2.14.11.jar
combatroll-fabric-1.3.3+1.20.4.jar
comforts-fabric-7.2.2+1.20.4.jar
conduitspreventdrowned-1.20.4-3.6.jar
Continents_1.20.x_v1.1.5.jar
continuity-3.0.0-beta.5+1.20.2.jar
Controlling-fabric-1.20.4-15.0.5.jar
cooldown-coordinator-0.6.3.jar
copperhopper-0.7.0+1.20.4.jar
CraterLib-Fabric-1.20.4-2.0.0.jar
cristellib-1.2.4-fabric.jar
crockpot-1.14.1+1.20.4.jar
cryingghasts-1.20.4-3.3.jar
ctov-3.4.4.jar
CustomWindowTitle-Fabric-1.20+v1.2.0.jar
dark-loading-screen-1.6.14.jar
darkbindings-fabric-1.20.2-1.20.4-1.4.0.jar
darksmelting-fabric-1.20.2-1.20.4-1.0.7.jar
darksmithing-fabric-1.20.2-1.20.4-1.0.7.jar
darktimer-fabric-1.20.3-1.20.4-1.1.2.jar
dcch-1.3.jar
Debugify-1.20.4+1.1.jar
despawningeggshatch-1.20.4-4.3.jar
DetailArmorBar-2.6.3+1.20.4-fabric.jar
DiagonalFences-v20.4.1-1.20.4-Fabric.jar
discerning-furnace-1.0.15+MC1.19-1.20.6.jar
DistantHorizons-2.1.2-a-1.20.4-forge-fabric.jar
DistinguishedPotions-v20.4.1-1.20.4-Fabric.jar
doubledoors-1.20.4-5.8.jar
DripSounds-1.19.4-0.3.2.jar
dynamic-fps-3.5.1+minecraft-1.20.0-fabric.jar
DynamicSoundFilters-1.4.0+1.20.4.jar
DynamicSurroundings-Fabric-1.20.4-0.3.3.jar
EasyAnvils-v20.4.6-1.20.4-Fabric.jar
easyelytratakeoff-1.20.4-4.2.jar
EasyMagic-v20.4.0-1.20.4-Fabric.jar
EasyShulkerBoxes-v20.4.6-1.20.4-Fabric.jar
eating-animation-1.20+1.9.61.jar
EchoChest-v20.4.1-1.20.4-Fabric.jar
edibles-1.20.4-4.3.jar
emi-1.1.8+1.20.4+fabric.jar
enchantingcommands-1.20.4-3.3.jar
EnchantingInfuser-v20.4.1-1.20.4-Fabric.jar
EnchantmentDescriptions-Fabric-1.20.4-20.0.4.jar
enhancedblockentities-0.10.1+1.20.4.jar
entityculling-fabric-1.6.6-mc1.20.4.jar
entity_model_features_fabric_1.20.4-2.0.2.jar
entity_texture_features_fabric_1.20.4-6.1.jar
EquipmentCompare-1.20.2-fabric-1.3.8.jar
erodingstoneentities-1.20.4-4.4.jar
exlinecopperequipment-v2.1.10-fabric-1.20.4.jar
exordium-fabric-1.2.1-mc1.20.4.jar
Explorify v1.6.1 f10-48.jar
ExtendedDrawers-2.1.1+mc.1.20.4.jar
extractpoison-1.20.4-3.3.jar
fabric-api-0.97.1+1.20.4.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
fabric-release-regrowth-1.20.4-96.31.1.jar
fabricskyboxes-0.7.3+mc1.20.2.jar
fallingleaves-1.15.6+1.20.1.jar
fallthroughslime-1.20.4-3.2.jar
fast-ip-ping-mc1.20.4-fabric-v1.0.3.jar
fastercrouching-1.20.4-2.5.jar
fastquit-3.0.0+1.20.4.jar
ferritecore-6.0.3-fabric.jar
firespreadtweaks-1.20.4-2.5.jar
fixedanvilrepaircost-1.20.4-3.3.jar
followersteleporttoo-1.20.4-2.4.jar
ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
FriendlyFire-Fabric-1.20.4-21.0.4.jar
furnacerecycle-1.20.4-2.2.jar
gf-compass-finder-0.8-1.20.4.jar
giantspawn-1.20.4-5.0.jar
globalpacks-fabric-20.3.1.jar
grabbymobs-1.20.4-1.5.jar
grapplemod-1.8+1.20.4.jar
grassseeds-1.20.4-3.2.jar
grind-enchantments-3.1.2+1.20.4.jar
grindstonesharpertools-1.20.4-3.5.jar
guardvillagers-2.0.9-1.20.4.jar
guifollowers-1.20.4-3.5.jar
handoveryouritems-1.20.4-3.3.jar
HangGlider-v20.4.2-1.20.4-Fabric.jar
healingcampfire-1.20.4-5.3.jar
healingsoup-1.20.4-4.8.jar
HeldItemTooltips-v20.4.1-1.20.4-Fabric.jar
hoetweaks-1.20.4-3.4.jar
HorseExpert-v20.4.1-1.20.4-Fabric.jar
huskdropsand-1.20.4-9-fabric.jar
huskspawn-1.20.4-3.5.jar
Iceberg-1.20.4-fabric-1.1.18.jar
icepreventscropgrowth-1.20.4-3.2.jar
IllagerInvasion-v20.4.3-1.20.4-Fabric.jar
ImmediatelyFast-Fabric-1.2.18+1.20.4.jar
improvedsignediting-1.20.4-1.1.jar
Incendium_1.20.x_v5.3.5.jar
indium-1.0.31+mc1.20.4.jar
infinitetrading-1.20.4-4.4.jar
inventoryhud.fabric.1.20.4-3.4.22.jar
InventoryProfilesNext-fabric-1.20.3-1.10.10.jar
inventorytotem-1.20.4-3.2.jar
iris-1.7.2+mc1.20.4.jar
ironbookshelves-1.20.4-1.3.1-fabric.jar
ironladders-1.20.4-2.1.51-fabric.jar
itemswapper-fabric-0.6.3-mc1.20.4.jar
jei-1.20.4-fabric-17.3.0.2.jar
konkrete_fabric_1.9.2_MC_1.20.4.jar
krypton-0.2.6.jar
lambdynamiclights-2.3.4+1.20.4.jar
lanserverproperties-1.12.1-fabric.jar
lanterns-belong-on-walls-1.7.0+1.20.4.jar
laserbridges-1.20.4-2-fabric.jar
lavasand-1.20.4-1-fabric.jar
LeavesBeGone-v20.4.1-1.20.4-Fabric.jar
LegendaryTooltips-1.20.2-fabric-1.4.5.jar
libIPN-fabric-1.20.3-4.0.2.jar
lithium-fabric-mc1.20.4-0.12.1.jar
lithostitched-fabric-1.20.4-1.1.5.jar
malilib-fabric-1.20.4-0.18.3.jar
manure-1.20.4-3.5.jar
MapTooltip-fabric-1.20-3.0.0.jar
mcw-bridges-3.0.0-mc1.20.4fabric.jar
mcw-doors-1.1.1fabric-mc1.20.4.jar
mcw-fences-1.1.2-mc1.20.4fabric.jar
mcw-furniture-3.2.2-mc1.20.4fabric.jar
mcw-lights-1.1.1-mc1.20.4fabric.jar
mcw-paths-1.0.5-1.20.4fabric.jar
mcw-roofs-2.3.0-mc1.20.4fabric.jar
mcw-trapdoors-1.1.3-mc1.20.4fabric.jar
mcw-windows-2.2.1-mc1.20.4fabric.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
MetalBundles-v20.4.4-1.20.4-Fabric.jar
midnightlib-fabric-1.5.3.jar
mineralchance-1.20.4-3.6.jar
minihud-fabric-1.20.4-0.30.2.jar
mixintrace-1.1.1+1.17.jar
Mo-Glass-1.7-MC1.20.4.jar
mobility-1.5.0.jar
MobLassos-v20.4.1-1.20.4-Fabric.jar
modelfix-1.14-fabric.jar
modernfix-fabric-5.17.0+mc1.20.4.jar
ModernKeyBinding-Fabric-1.20.4-1.3.0.jar
modmenu-9.2.0.jar
moonlight-1.20.4-2.10.3-fabric.jar
moreadvancementsmod-1.5.1-1.20.4.jar
moreculling-1.20.4-0.24.0.jar
moremobvariants-fabric+1.20.4-1.3.0.1.jar
morevanillashields-1.0.2-1.20.4.jar
MouseTweaks-fabric-mc1.20-2.26.jar
moveboats-1.20.4-3.2.jar
moveminecarts-1.20.4-3.4.jar
multirecipe-fabric-0.49.2_1.20.4(1).jar
mvs-4.1.2-1.20-fabric.jar
namepain-1.5.3 fabric-1.20.x.jar
nautilus-1.0.0.jar
nemos-better-mending-1.1.1-1.20.4.jar
netherportalspread-1.20.4-8.1.jar
netherrackblasting-1.20.4-0-fabric.jar
NoChatReports-FABRIC-1.20.4-v2.6.1.jar
nohostilesaroundcampfire-1.20.4-5.9.jar
noisium-fabric-2.0.3+mc1.20.2-1.20.4.jar
notenoughanimations-fabric-1.7.4-mc1.20.4.jar
Nullscape_1.20.x_v1.2.6.jar
nutritiousmilk-1.20.4-3.3.jar
nvidium-0.2.6-beta.jar
omnihopper-2.2.4+1.20.4.jar
optigui-2.3.0-beta.2.jar
oreharvester-1.20.4-1.3.jar
packetfixer-fabric-1.4.1-1.20.2-to-1.20.4.jar
paginatedadvancements-2.4.2.jar
panorama_screens-1.0+fabric+mc1.20.4.jar
paperbooks-1.20.4-3.2.jar
PaperDoll-v20.4.1-1.20.4-Fabric.jar
passiveendermen-1.20.4-4.6.jar
passiveshield-1.20.4-3.4.jar
Patchouli-1.20.4-85-FABRIC.jar
PermanentSponges-v20.4.1-1.20.4-Fabric.jar
Philips-Ruins1.20.4-2.3[Fabric].jar
physics-mod-pro-v169f-fabric-1.20.4.jar
player-animation-lib-fabric-1.0.2-rc1+1.20.4.jar
PlentyPlates-v20.4.1-1.20.4-Fabric.jar
Prism-1.20.4-fabric-1.0.6.jar
ProPlacer-v20.4.0-1.20.4-Fabric.jar
PuzzlesLib-v20.4.52-1.20.4-Fabric.jar
qu-enchantments-1.3.8-1.20.4.jar
quickpaths-1.20.4-3.3.jar
quickrightclick-1.20.4-1.4.jar
quicksort-0.8.0+1.20.4.jar
raised-fabric-1.20.4-3.1.3.jar
randomvillagenames-1.20.4-3.5.jar
realisticbees-1.20.4-3.8.jar
redstonepen-1.20.4-fabric-1.8.32.jar
reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar
Remastered Structure 1.20.4-0.4 fabric.jar
replantingcrops-1.20.4-5.3.jar
repurposed_structures-7.3.5+1.20.4-fabric.jar
ResourcePackOverrides-v20.4.2-1.20.4-Fabric.jar
Resourcify (1.20.2-1.20.4-fabric)-1.4.0.jar
RespawningAnimals-v20.4.0-1.20.4-Fabric.jar
sawmill-1.20.4-1.3.1-fabric.jar
Searchables-fabric-1.20.4-1.0.6.jar
servercore-fabric-1.5.0+1.20.4.jar
servercountryflags-1.10.1-1.20.4-FABRIC.jar
skeletonhorsespawn-1.20.4-3.8.jar
skinlayers3d-fabric-1.6.6-mc1.20.4.jar
slabstoblocks-1.20.4-1-fabric.jar
smarterfarmers-1.20.4-1.8.3-fabric.jar
smeltingstone-1.20.4-0-fabric.jar
snowballsfreezemobs-1.20.4-3.3.jar
sodium-extra-0.5.4+mc1.20.4-build.116.jar
sodium-fabric-0.5.8+mc1.20.4.jar
spark-1.10.58-fabric.jar
spidersproducewebs-1.20.4-3.3.jar
SpikySpikes-v20.4.1-1.20.4-Fabric.jar
StackDeobfuscatorFabric-1.4.2+bf1fc22.jar
starlight-1.1.3+fabric.f5dcd1a.jar
Statement-4.2.9+1.14.4-1.20.4.jar
status-effect-bars-1.0.4.jar
Stoneworks-v20.4.0-1.20.4-Fabric.jar
StrawStatues-v20.4.1-1.20.4-Fabric.jar
Structory_1.20.x_v1.3.5.jar
Structory_Towers_1.20.x_v1.0.7.jar
suggestion-tweaker-1.20-1.5.2-fabric.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.2.jar
supermartijn642corelib-1.1.17a-fabric-mc1.20.4.jar
SwordBlockingMechanics-v20.4.1-1.20.4-Fabric.jar
terralith-biome-saplings-1.1.0c.jar
Terralith_1.20_v2.5.1.jar
thornybushprotection-1.20.4-1.2.jar
tidal-towns-1.3.jar
TinySkeletons-v20.4.1-1.20.4-Fabric.jar
ToolStats-Fabric-1.20.4-19.0.3.jar
trade-cycling-fabric-1.20.4-1.0.11.jar
transcendingtrident-1.20.4-4.6.jar
travelersbackpack-fabric-1.20.4-9.4.6.jar
travelerscompass-1.20.4-3.0.3b-fabric.jar
TravelersTitles-1.20.4-Fabric-4.4.1.jar
treeharvester-1.20.4-8.7.jar
tweakable-levels-1.0.1.jar
t_and_t-1.13.1b.jar
underwaterenchanting-1.20.4-2.7.jar
UniversalBoneMeal-v20.4.2-1.20.4-Fabric.jar
vanilla_degus-1.20.3+-v1.5.2-fabric.jar
videotape-1.3.0.jar
villagerdeathmessages-1.20.4-3.3.jar
villagerfollows-v1.1.6-fabric-1.20.4.jar
villagernames-1.20.4-7.3.jar
VisualWorkbench-v20.4.2-1.20.4-Fabric.jar
voicechat-fabric-1.20.4-2.5.17.jar
water-erosion-1.20.4-fabric-1.1.6.jar
waveycapes-fabric-1.4.7-mc1.20.4.jar
waystones-fabric-1.20.4-16.0.5.jar
weakerspiderwebs-1.20.4-3.4.jar
wooltostring-v1.1.5-fabric-1.20.4.jar
wooltweaks-1.20.4-3.3.jar
wthit-fabric-10.9.3.jar
XaerosWorldMap_1.38.8_Fabric_1.20.4.jar
Xaeros_Minimap_24.2.0_Fabric_1.20.4.jar
YetAnotherConfigLib-3.5.0+1.20.4-fabric.jar
yosbr-0.1.2.jar
YungsApi-1.20.4-Fabric-4.4.3.jar
YungsBetterDesertTemples-1.20.4-Fabric-3.4.4.jar
YungsBetterDungeons-1.20.4-Fabric-4.4.4.jar
YungsBetterJungleTemples-1.20.4-Fabric-2.4.4.jar
YungsBetterMineshafts-1.20.4-Fabric-4.4.2.jar
YungsBetterNetherFortresses-1.20.4-Fabric-2.4.4.jar
YungsBetterOceanMonuments-1.20.4-Fabric-3.4.3.jar
YungsBetterStrongholds-1.20.4-Fabric-4.4.3.jar
YungsBetterWitchHuts-1.20.4-Fabric-3.4.3.jar
YungsBridges-1.20.4-Fabric-4.4.2.jar
YungsExtras-1.20.4-Fabric-4.4.2.jar
zombiehorsespawn-1.20.4-4.8.jar
zombieproofdoors-1.20.4-3.2.jar
Zoomify-2.14.0+1.20.4.jar

### Server

Happens

### Client

Happens

### Logs

See description.

**Comment by TommyC81** [comment]
Just want to add that I'm not experiencing the same issue with Cable configuration not being saved on Minecraft 1.21 (v4.0.0 [1.21] from 29 June 2024). The way to access the Cable configuration does however require that you don't have a shield in the off-hand, which is somewhat cumbersome.

**Comment by MattiDragon** [comment]
I'll close this as the main issue was fixed, and as I said in #20 the clicking is hard to implement
