### ISSUE TITLE
[Feature]: Sneak and right-click with wrench/stick to configure cables

### ISSUE THREAD

**Issue by TommyC81** [MattiDragon/AdvancedNetworking#20]
### Description of the feature

It is currently required to sneak and right-click with an empty hand to configure cables. However, the off-hand also needs to be empty, which makes it unnecessarily cumbersome to configure cables. Suggest that simply sneaking and right-clicking with wrench/stick should be sufficient to configure a cable. This could potentially be an optional setting.

### How does it make the mod better?

Make it quicker/easier to place and configure network cables.

**Comment by MattiDragon** [comment]
This seems like a good idea, but minecraft is designed such that sneak-clicking on blocks with an item forces the item to be used, even if it doesn't have any action. Implementing this would require a lot of work
