### ISSUE TITLE
[Feature]: Support for transferring compostable items to a compost bin

### ISSUE THREAD

**Issue by PTALTS-LK** [MattiDragon/AdvancedNetworking#23]
### Description of the feature

Makes "Item Transfer" support for transferring compostable items to the compost bin for composting, and also allows it to be used to remove bone meal from the compost bin

### How does it make the mod better?

Make this mod more useful

**Comment by MattiDragon** [comment]
This should just work. If it doesn't then it's probably a bug in fabric api

**Comment by PTALTS-LK** [comment]
> This should just work. If it doesn't then it's probably a bug in fabric api

I built a structure like the one below to test and it didn't work
![image](https://github.com/user-attachments/assets/b20ac624-54ca-47aa-850c-1123056e02f8)
![image](https://github.com/user-attachments/assets/93165eac-5204-4f72-aaad-3d82a9537430)
![image](https://github.com/user-attachments/assets/d9fcfacf-3e80-40b5-b7c2-8680ab15401b)

fabric: 0.16.4
AN: 4.0.0 1.21

**Comment by MattiDragon** [comment]
I just noticed something. Composters only support inserting items from the top and extracting from the bottom. You'll have to place your interfaces as such for it to work.
