### ISSUE TITLE
Character limit on item ID field.

### ISSUE THREAD

**Issue by beep-beep-beep-boop** [MattiDragon/AdvancedNetworking#6]
Hi, the field for the item IDs, for example in the "Item Count" node, has a character limit which makes items with long ID names unable to be typed into them. for example, "modern_industrialization:copper_dust". The character limit seems like it's 32 characters.

(this is on 1.19.2)

**Comment by MattiDragon** [comment]
Minecraft has a default limit. Seems like I forgot to change it

**Comment by MattiDragon** [comment]
Fixed in v1.0.1
