### ISSUE TITLE
[Bug]: Interface selection menu only works with keyboard naviagtion

### ISSUE THREAD

**Issue by vahaala** [MattiDragon/AdvancedNetworking#7]
### Description of the issue

I tried to make a simple setup, to test this mod in creative. I connected the cables, set the block facing sides to interface mode, named them, and placed down a Network Controller. When I add an Item Transfer node, for example Item Source, then try to configure it with the Controller, the nodes aren't clickable at all inside the interface, and an error message saying that interface ID is invalid shows up. Nothing I do seems to work. It looks like there are checkboxes to select, and choose which interface(s) is the target for the node, but these don't work.

![obraz](https://user-images.githubusercontent.com/5729654/226985586-97d10271-bd05-43be-933d-1ffea3f104f3.png)
![obraz](https://user-images.githubusercontent.com/5729654/226985640-5d3af5c9-ee6d-4e5c-8568-ddd1cb4f925c.png)
![obraz](https://user-images.githubusercontent.com/5729654/226986560-3011fd13-820c-43de-b4a1-edb45b79b5c3.png)

Screenshots are taken on modded client, but I've tried it also with just the Fabric API installed, and the issue persists.
Unfortunately there seems to be no wiki of any sort to help me with figuring things out.

### Reproduction steps

1. Build a simple network.
2. Add some nodes in Network Controller.
3. Try to configure which interfaces will be active for any node.

### Mod version

1.0.2

### Operating System

Windows 11

### Minecraft version

1.19.4

### Other mods

Fabric API: 0.76.0

### Server

Not tested

### Client

Happens

### Logs

N/A, not a hard crash or anything

### Extra Context

Happens under both Fabric and Quilt loaders, with their newest respective APIs.

**Comment by MattiDragon** [comment]
It says invalid interface id because no interface is selected (the error is slightly outdated). Did you try clicking the checkboxes?

**Comment by vahaala** [comment]
> Did you try clicking the checkboxes?

That's exactly the issue, maybe I should have mentioned it more clearly - the checkboxes don't work at all. I cannot click them, they don't react to any input.

**Comment by MattiDragon** [comment]
That's weird. I'll check tomorrow.

And yes, this bug report should have been "check boxes don't work"

**Comment by MattiDragon** [comment]
I can't reproduce this with just advanced networking and fabric api. Did you use the wrong mouse button or something?

**Comment by vahaala** [comment]
> Did you use the wrong mouse button or something?

I found something interesting trying to verify it again - as before, with just this mod and Fabric API loaded.
While the Controller menu is unresponsive to mouse, it responds to _keyboard input_. I had to select the nodes using arrow keys (WASD that I use for movement doesn't work), and then Enter to select. The connections work this way, and the items transfer properly once I set up the rules. I never changed any controls setting, besides maybe remapping the inventory button but that's it.

**Comment by MattiDragon** [comment]
I'm confused about what you describing as the issue. I thought the issue was that you couldn't interact with the checkboxes in the config screen, but now you are saying that the main controller screen is broken?

**Comment by vahaala** [comment]
> I'm confused about what you describing as the issue

I apologize, let me write it up as a short list:

-I couldn't configure any sort of connections, because the checkboxes were uninteractive on the config screen, they didn't react at all to my clicking
-you mentioned it works fine on your end, so I tested a little bit more, and found out the checkboxes only respond to keyboard, not mouse - I have to use arrows and Enter key to select them

Hopefully that clears things up a bit? I don't really know how else I could describe the issue.

**Comment by MattiDragon** [comment]
I understand now. I was just confused as you used the wrong terminology. In the code connections are connections between nodes in the editor. Source and target node store an interface that they are connected to that can be selected from the list. The error message is misleading because it's from before the checkboxes when you have to copy paste the ID manually.

I still have no idea what the actual problem might be, but at least I understand it now.

Btw if you like you could join the discord as this will probably need significant back and forth to get fixed

**Comment by MattiDragon** [comment]
Ok, I figured it out, clicking only works on some gui scales, for some reason.

**Comment by MattiDragon** [comment]
An update fixing this will be out shortly
