### ISSUE TITLE
[Bug]:  Energy Transfer rate in Config is doesn't work

### ISSUE THREAD

**Issue by bakrun** [MattiDragon/AdvancedNetworking#8]
### Description of the issue

default Energy transfer rate is 256  but energy transfer rate work 128 and modify energy transfer rate doesn't work.  rate modify less than 128, it's work but not work greater than 128

### Reproduction steps

1. Install generators(generate greater than 128) and power consuming blocks and connect them to the network Controllers.
2. use controller energy source(generator) -> energy target(consume block) 
3. Observe energy transfers 128 at a time
4. edit config energy transfer rate greater than 128
5. Observe energy transfers 128 at a time
6. edit config energy transfer rate less than 128
7.  Observe energy transfers rate is work

### Mod version

1.0.3

### Operating System

Windows 10

### Minecraft version

1.19.4

### Other mods

fabric-api-0.76.0+1.19.4
energizedpower-1.19.4-1.5.0-fabric

### Server

Not tested

### Client

Happens

### Logs

https://pastebin.com/Y114XYaw

**Comment by MattiDragon** [comment]
This was caused by the target storage transfer limit
