### ISSUE TITLE
[Bug]: ID Field in Item Count Node has default length of 32 characters

### ISSUE THREAD

**Issue by lilmayu** [MattiDragon/AdvancedNetworking#9]
### Description of the issue

ID Field in the Item Count Node has a default length of 32 characters. This is problematic for long IDs. I suppose it is just a small oversight because other fields have changed max lengths.

https://github.com/MattiDragon/AdvancedNetworking/blob/8eb651e80480298cae799e4651429a82545746e4/src/main/java/io/github/mattidragon/advancednetworking/graph/node/item/info/ItemCountNode.java#L211

There may be more fields that also do not change the maximum length, but I haven't checked others.

### Reproduction steps

1. Type something longer in the ID Field within Item Count Node
2. :( no space

### Mod version

v1.0.3

### Operating System

Windows 10

### Minecraft version

1.19.4

### Other mods

Not important (I am too lazy to open cmd and type `dir /b`)

### Server

Doesn't happen

### Client

Happens

### Logs

Not important as well

### Extra Context

I wanted to post this as a feature request, but *technically* it is a bug.

(yet again, here I am, writing an issue, hope you have a nice day)

**Comment by MattiDragon** [comment]
I'll fix this the next time I update to mod. Seems like I missed one
